version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  builder: singlehtml
  configuration: doc/conf.py

formats:
  - htmlzip

python:
  install:
    - requirements: requirements-dev.txt
