name: PyPI deploy

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  pypi-deploy:
    name: Deploying Python Package
    runs-on: ubuntu-20.04
    permissions:
      id-token: write

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      name: Install Python
    
    - name: Build source distribution
      run: |
        python setup.py sdist

    - uses: pypa/gh-action-pypi-publish@v1.8.14
